### ISSUE TITLE
Does the function work correctly?

### ISSUE THREAD

**Issue by tampiss** [DenisMtfl/node-red-contrib-dynamic-thermostat#31]
Hi, 
just upgraded from 0.0.4 to 0.0.8 and it broke my set up -> I had to reverse back. Never mind.. 

Looking into your code, I was curious if the conditions are as their supposed to be..

      if (node.current !== undefined && node.target !== undefined && node.hysteresis !== undefined) {
        statusColor = 'green'
        if (node.switch === false) {
          result = Calc(node.current, node.target, node.hysteresis)
        } else {
          result = true
        }
      }

      this.status({ fill: statusColor, shape: 'dot', text: `Current: ${node.current}  Target: ${node.target} Hysteresis: ${node.hysteresis} Switch: ${node.switch}` })
      msg = { payload: { onoff: result, switch: node.switch, current: node.current, target: node.target, hysteresis: node.hysteresis } }
      node.send(msg)

Does it mean you do the re-calc when switch is off, but no when it is on - so that the onoff will always be true no matter the current, target and hysteresis values.

M.

UPDATE:
I believe it should be

    if (node.switch === true) {
      result = Calc(node.current, node.target, node.hysteresis)
    } else {
      result = false
    }

**Comment by solderpump** [comment]
Hello,

I have noticed the same problem, that the onoff output state is always true. If this fix could be implemented in the next update I would like to test it as well. This is a perfect node for my use case.

**Comment by Caprico85** [comment]
> I believe it should be
> ```
> if (node.switch === true) {
> ```

This would work as long nobody sends in a message with `switch = false`. Then the thermostat would still always be switched on. But judging by the readme `false` is a perfectly valid value.

The readme says:
> topic: switch, payload: true/false, you can force to switch on or off the thermostat

It's not clear how the `switch parameter was intended to work. Does it switch on the thermostat only once and the next temperature message would set it back to automatic mode? Or does it force the thermostat to stay on/off forever regardless of temperature messages, until it is set back to automatic mode?

The first case would not make much sense. Most sensors send their temperature every few seconds. So the thermostat would only stay on/off for a few seconds.

So it must be the second case: With a `switch`message, the thermostat is "locked" to on or off.

For this to work, the `switch` parameter would need a third state. `true` for always on, `false` for always off and a new state null/auto/whatever to bring the thermostat back into automatic mode. The if condition needs to be changed to something like this:

```js
if(node.switch === true) {
    // automatic switching disabled, always stay on
    result = true
} else if(node.switch === false) {
    // automatic switching disabled, always stay off
    result = false
} else {
    // automatic switching enabled
    result = Calc(...)
}
```

Additionally, `node.switch` needs to be initialized to `null` (instead of `true`).

**Comment by Caprico85** [comment]
I have send pull request #45 with my changes to fix this.

**Comment by DenisMtfl** [comment]
#33
